export const schedulesInit = [
  {
    key: 0,
    hora: '00:00',
    lunes: 'N/A',
    martes: 'N/A',
    miercoles: 'N/A',
    jueves: 'N/A',
    viernes: 'N/A',
    sabado: 'N/A',
    domingo: 'N/A',
  },
  {
    key: 2,
    hora: '02:00',
    lunes: 'N/A',
    martes: 'N/A',
    miercoles: 'N/A',
    jueves: 'N/A',
    viernes: 'N/A',
    sabado: 'N/A',
    domingo: 'N/A',
  },
  {
    key: 4,
    hora: '04:00',
    lunes: 'N/A',
    martes: 'N/A',
    miercoles: 'N/A',
    jueves: 'N/A',
    viernes: 'N/A',
    sabado: 'N/A',
    domingo: 'N/A',
  },
  {
    key: 6,
    hora: '06:00',
    lunes: 'N/A',
    martes: 'N/A',
    miercoles: 'N/A',
    jueves: 'N/A',
    viernes: 'N/A',
    sabado: 'N/A',
    domingo: 'N/A',
  },
  {
    key: 8,
    hora: '08:00',
    lunes: 'N/A',
    martes: 'N/A',
    miercoles: 'N/A',
    jueves: 'N/A',
    viernes: 'N/A',
    sabado: 'N/A',
    domingo: 'N/A',
  },
  {
    key: 10,
    hora: '10:00',
    lunes: 'N/A',
    martes: 'N/A',
    miercoles: 'N/A',
    jueves: 'N/A',
    viernes: 'N/A',
    sabado: 'N/A',
    domingo: 'N/A',
  },
  {
    key: 12,
    hora: '12:00',
    lunes: 'N/A',
    martes: 'N/A',
    miercoles: 'N/A',
    jueves: 'N/A',
    viernes: 'N/A',
    sabado: 'N/A',
    domingo: 'N/A',
  },
  {
    key: 14,
    hora: '14:00',
    lunes: 'N/A',
    martes: 'N/A',
    miercoles: 'N/A',
    jueves: 'N/A',
    viernes: 'N/A',
    sabado: 'N/A',
    domingo: 'N/A',
  },
  {
    key: 16,
    hora: '16:00',
    lunes: 'N/A',
    martes: 'N/A',
    miercoles: 'N/A',
    jueves: 'N/A',
    viernes: 'N/A',
    sabado: 'N/A',
    domingo: 'N/A',
  },
  {
    key: 18,
    hora: '18:00',
    lunes: 'N/A',
    martes: 'N/A',
    miercoles: 'N/A',
    jueves: 'N/A',
    viernes: 'N/A',
    sabado: 'N/A',
    domingo: 'N/A',
  },
  {
    key: 20,
    hora: '20:00',
    lunes: 'N/A',
    martes: 'N/A',
    miercoles: 'N/A',
    jueves: 'N/A',
    viernes: 'N/A',
    sabado: 'N/A',
    domingo: 'N/A',
  },
  {
    key: 22,
    hora: '22:00',
    lunes: 'N/A',
    martes: 'N/A',
    miercoles: 'N/A',
    jueves: 'N/A',
    viernes: 'N/A',
    sabado: 'N/A',
    domingo: 'N/A',
  },
];